filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - /var/log/ugc/*.json
  multiline.pattern: '^\['
  multiline.negate: true
  multiline.match: after
  fields:
    service_name: ugc
  tags: [ "ugc" ]
  json:
    keys_under_root: true
    add_error_key: true

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]
