version: "3.9"
services:
  logstash:
    image: logstash:8.10.2
    environment:
      # Так как сейчас вы хотите запустить logstash без Elasticsearch, необходимо отключить встроенный мониторинг, отправляющий данные в ES
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: "elasticsearch:9200"
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044/udp"
    volumes:
      # Монтируем файл с конфигурацией logstash
      - ./logstash/logstash.conf:/config/logstash.conf:ro
    # Запускаем с указанием конфигурационного файла
    command: logstash -f /config/logstash.conf

  # Обратите внимание: не стоит использовать для ELK тот же ES, который задействован для полнотекстового поиска в вашем сервисе
  elasticsearch:
    image: elasticsearch:8.10.2
    environment:
      # Указываем ES запуститься в одном экземпляре
      - discovery.type=single-node
      # Пока не будем беспокоиться о безопасности
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    volumes:
      - ./elastic/data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.10.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  flask-app:
    env_file:
      - .env
    build:
      context: ./flask_app
      dockerfile: ./docker/Dockerfile
    ports:
      - "5005:5000"
    volumes:
      - ./flask_app/src:/code

  nginx:
    image: nginx:1.19.2
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/config/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - flask-app
    ports:
      - 8080:80
