version: '3'

services:
  vertica:
    image: jbfavre/vertica:latest
    ports:
      - "5435:5433"
      - "5444:5444"

  clickhouse:
    image: clickhouse/clickhouse-server:23
    container_name: clickhouse
    hostname: clickhouse
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
